version: '3'

services:
  mongo-gui:
    image: cowboybkit/mongo-gui:v1
    build: .
    restart: always
    ports:
      - "4321:4321"
    environment:
      - MONGO_URL=mongodb://192.168.1.4:27017
      - SUBPATH=/mongodev